name: Sync to GitLab

on:
  push:
    branches:
      - '**'
  delete:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (full history)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          GITLAB_URL="https://gitlab.com/rosakalista/sistem-magang_hambaAllah.git"
          git remote add gitlab "$GITLAB_URL"
          git push gitlab --all --force
          git push gitlab --tags --force